### ISSUE TITLE
不知道作者是否还在维护，希望作者看看

### ISSUE THREAD

**Issue by Estelle00** [xuanjinliang/fis-postpackager-jpgtowebp#1]
1、生成文件目录位置异常不会直接push到内置服务器上
2、读取HTML文件时使用的为源文件，会覆盖掉之前编译的内容
3、是否考虑JS内引用图片的情况，如：预加载图片

**Comment by xuanjinliang** [comment]
1、fis.match(/\/static\/(.*)/i, {
    release: '/staticPub/$1', 
    url: '/staticPub/$1' 
});

2、逻辑本来就是会替换，可以把插件放到最后执行；
3、预加载目前不考虑加入；
